# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               Felix Lucka
tagline:             academic website
url:                 http://felixlucka.github.io/
paginate:            5
baseurl:             ''
#baseurl:             http://felixlucka.github.io/

# Assets
#


# About/contact
author:
  name:              Felix Lucka
  email:             f.lucka@ucl.ac.uk

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/FelixLucka/FelixLucka.github.io



defaults:
-
  scope:
    path: ""
  values:
    layout: "default"
    author: "Felix Lucka"
-
  scope:
    path: "research"
  values:
    layout: "defaultAlter1" # overrides previous default layout
-
  scope:
    path: "teaching"
  values:
    layout: "defaultAlter2" # overrides previous default layout
-
  scope:
    path: "contact&about"
  values:
    layout: "defaultAlter2" # overrides previous default layout


gems: [jekyll-paginate]
